# Basic Information
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.4.4
maven_group=hainer.mod
archives_base_name=achievementstyle

# Minecraft & Fabric
minecraft_version=26.2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT


# Dependencies
fabric_api_version=0.157.0+26.2
yacl_version=3.9.5+26.2-fabric
modmenu_version=20.0.2